source 'https://rubygems.org'


gem 'rails', '4.1.2'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'devise'
gem 'noty-rails'
gem 'paperclip', '~> 4.1'
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'spring',        group: :development
gem "letter_opener", :group => :development

gem 'pry'

group :developement, :test do
  gem 'rspec-rails', '~> 3.0.0'
  gem 'capybara', '~> 2.3.0'
end
